### ISSUE TITLE
소스관리 문제점

### ISSUE THREAD

**Issue by zauin** [zauin/zauin_work#1]
소스관리 힘드네요

**Comment by verotas** [comment]
안녕하세요.

저희는 (주)자우인 이라는 회사입니다. zauin.com 을 소유하고 있고요.
github 사이트를 이용하는데 zauin 계정을 먼저 등록하셨는데, 별로 사용은 하지 않으시는 것 같네요.
괜찮으시다면 저희한테 zauin 계정을 양보해 주실 수 있을런지요? 필요하다면 어느 정도 보상도 생각하고 있습니다.

이 글 보시게 되면, 연락 주시면 고맙겠습니다.

cto@zauin.com / 02-586-2710

감사합니다.
